In [1]:
import numpy as np

In [2]:
#buat vector x dan y dengan ukuran 1x3 menggunakan numpy
x = np.array([18, 1, 8])
x

array([18,  1,  8])

In [3]:
#buat vector x dan y dengan ukuran 1x3 menggunakan numpy
y = np.array([8, 1, 81])
y

array([ 8,  1, 81])

In [4]:
import torch

In [7]:
#buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
x_pt = torch.tensor([18, 1, 8])
x_pt

tensor([18,  1,  8])

In [6]:
#buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
y_pt = torch.tensor([8, 1, 81])
y_pt

tensor([ 8,  1, 81])

In [8]:
import tensorflow as tf

In [9]:
#buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
x_tf = tf.Variable([18, 1, 8])
x_tf


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([18,  1,  8], dtype=int32)>

In [10]:
#buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
y_tf = tf.Variable([8, 1, 81])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 8,  1, 81], dtype=int32)>

In [11]:
#hitung perkalian dot product antara vector x dan vector y
np.dot(x, y)

np.int64(793)

In [12]:
#hitung perkalian dot product antara vector x_pt dan vector y_pt
torch.dot(x_pt, y_pt)

tensor(793)

In [13]:
#hitung perkalian dot product antara vector x_tf dan vector y_tf
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=793>