In [1]:
import numpy as np

In [2]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[18, 81], [1, 8], [25, 15]])
X

array([[18, 81],
       [ 1,  8],
       [25, 15]])

In [3]:
#hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(148)

In [11]:
import tensorflow as tf

In [13]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[18, 81], [1, 8], [25, 15]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[18, 81],
       [ 1,  8],
       [25, 15]], dtype=int32)>

In [14]:
#hitung hasil penjumlahan seluruh elemen matrix X
X.sum(axis=0)


array([ 44, 104])

In [15]:
#hitung hasil penjumlahan seluruh elemen matrix X
X.sum(axis=1)

array([99,  9, 40])

In [16]:
#hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99,  9, 40], dtype=int32)>

In [17]:
import torch

In [18]:
X_pt = torch.tensor([[18, 81], [1, 8], [25, 15]])
X_pt

tensor([[18, 81],
        [ 1,  8],
        [25, 15]])

In [19]:
#hitung hasil penjumlahan seluruh elemen matrix X_pt
torch.sum(X_pt)

tensor(148)

In [22]:
#hitung hasil penjumlahan matrix X berdasarkan row nya
sum(X, 1)

array([ 45, 105])

In [24]:
#hitung hasil penjumlahan matrix X_pt berdasarkan row nya
torch.sum(X_pt, 1)

tensor([99,  9, 40])

In [28]:
#hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99,  9, 40], dtype=int32)>

In [30]:
#hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(0)

array([ 44, 104])

In [31]:
#hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
torch.sum(X_pt, 0)

tensor([ 44, 104])

In [32]:
#hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 44, 104], dtype=int32)>

In [38]:
#hitung nilai minimal dari matrix X, X_pt dan X_tf
min_X = X.min()
min_X_pt = X_pt.min()
min_X_tf = tf.reduce_min(X_tf)
print(min_X, min_X_pt, min_X_tf)


1 tensor(1) tf.Tensor(1, shape=(), dtype=int32)


In [39]:
#hitung nilai rata-rata dari matrix X, X_pt dan X_tf
max_X = X.max()
max_X_pt = X_pt.max()
max_X_tf = tf.reduce_max(X_tf)
print(max_X, max_X_pt, max_X_tf)

81 tensor(81) tf.Tensor(81, shape=(), dtype=int32)


In [40]:
X.prod

<function ndarray.prod>

In [41]:
#hitung hasil perkalian seluruh elemen matrix X
X.prod()

np.int64(4374000)

In [42]:
#hitung hasil perkalian seluruh elemen matrix X_pt
torch.prod(X_pt)

tensor(4374000)

In [43]:
#hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=4374000>