Tensor Transpotition

In [2]:
import numpy as np
import torch
import tensorflow as tf


In [3]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[18, 8], [1, 8], [2, 5]])
X

array([[18,  8],
       [ 1,  8],
       [ 2,  5]])

In [8]:
#matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[18, 8], [1, 8], [2, 5]])
X_pt

tensor([[18,  8],
        [ 1,  8],
        [ 2,  5]])

In [7]:
#matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[18, 8], [1, 8], [2, 5]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[18,  8],
       [ 1,  8],
       [ 2,  5]], dtype=int32)>

In [9]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18,  1,  2],
       [ 8,  8,  5]], dtype=int32)>